service: serverless-demo

frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1

  environment:
    key : knknd  

plugins:
  - serverless-offline

functions:
  initial:
    handler: handler.lambda
    events:
      - http: 
          path: /hello
          method: get
